version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: contactuser
      POSTGRES_PASSWORD: contactpass
      POSTGRES_DB: contactdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: contactuser
      DB_PASS: contactpass
      DB_NAME: contactdb
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  pgdata:
