architecture: replication
replicaCount: 3

auth:
  username: contactuser
  password: contactpass
  database: contactdb

primary:
  persistence:
    storageClass: longhorn
    size: 2Gi

readReplicas:
  persistence:
    storageClass: longhorn
    size: 2Gi
